### ISSUE TITLE
bla_giveubigun

### ISSUE THREAD

**Issue by PackSciences** [ntrf/blamod#7]
Bla_giveubigun gives the ubigun after save deletion, but couldn't you make it so that it directly switches to the ubi gun ?

**Comment by ntrf** [comment]
No. The way it works in this game - you have to pick up the gun in order for it to be operational. That's is why `give` command creates a weapon under player's feet. The exact moment when gun will be available to player depends on physics system. Therefore i have no knowlege when gun is actually available to player in order to switch to it.
