### ISSUE TITLE
Can't Find Background image on-start crash

### ISSUE THREAD

**Issue by TheHatMate** [ntrf/blamod#8]
My game starts up in a pitch black screen
After a couple seconds I get the error "Can't find background image 'materials/console/background01_widescreen.vtf'"

I've reinstalled blamod and Source SDK Base 2013 several times, but I get the exact same error.

**Comment by ntrf** [comment]
currently i recommend installing everything into one steam library on one disk drive, so your HL2, source SDK and blamod are inside the same `steamapps` directory. Theoretically you're only required to have `Source SDK Base 2013 Singleplayer` `Half-Life 2` in the same directory (most likely called `Common`) and blamod location is not important.

If that is not the case:
Several people had problems with this mod before, because they had very old pre-steampipe instalation of HL2 mixed with steampipe instalation somehow. In this case even if game works you might experience problems with save files or failing save-deletion. In this case you will need to unistall HL2, all episodes and all SDKs, delete folder `steamapps/Common/Half-Life 2` and `steamapps/Common/Source SDK ...` manually and then reinstall everything.

Finally i've had reports of Source SDK being installed, but not working untill you run it at least once. I'm not sure it's true, but you're welcome to try. You can start a "Video stress test" from SDK through steam tools menu. Just double-click on "Source SDK 2013 Singleplayer" and that should do it.

**Comment by ntrf** [comment]
Probably irrelevant. Closing
